/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import logins.welcome;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static logins.search.name;

/**
 *
 * @author keval
 */
public class fetch extends javax.swing.JFrame {
 static String name,role,batting_style,bowling_style,dob,team;
static int age,batt,bato,bat2,bowlt,bowlo,bowl2,allt,allo,all2,matchest,matcheso,matches2,runt,runo,run2,heighestt,heighesto,heighest2,averaget,averageo,average2,averagest,averageso,averages2,maidenst,maidenso,maidens2,wicketst,wicketso,wickets2;
    /**
     * Creates new form fetch
     */
    public fetch() {
        initComponents();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 49, 22));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 42, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DOB");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("AGE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, 22));

        jTextField3.setBackground(new java.awt.Color(204, 255, 204));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, -1));

        jTextField4.setBackground(new java.awt.Color(204, 255, 204));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 71, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ROLE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BATTING STYLE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, 22));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("BOWLING STYLE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jTextField5.setBackground(new java.awt.Color(204, 255, 204));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 177, 110, -1));

        jTextField6.setBackground(new java.awt.Color(204, 255, 204));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 204, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TEAM");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 20));

        jTextField7.setBackground(new java.awt.Color(204, 255, 204));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 87, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("IIC RANKING");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 123, 33));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("BAT");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 304, 35, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("BOWL");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 325, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("ALL");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 346, 35, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("BATTING");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 109, 27));

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEST", "ODI", "T20"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 240, 30));

        jLabel14.setText("MATCHES");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 20));

        jLabel15.setText("RUNS");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 20));

        jLabel16.setText("HIGHEST");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 20));

        jLabel17.setText("AVERAGE");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("BOWLING");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 542, 91, 35));

        jTable3.setBackground(new java.awt.Color(204, 255, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEST", "ODI", "T20"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 240, 30));

        jLabel19.setText("MATCHES");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 614, 60, 20));

        jLabel20.setText("WICKETS");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, 20));

        jLabel21.setText("AVERAGE");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, 20));

        jLabel22.setText("MAIDENS");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, 20));

        jTextField8.setBackground(new java.awt.Color(204, 255, 204));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 60, -1));

        jTextField9.setBackground(new java.awt.Color(204, 255, 204));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, -1));

        jTextField10.setBackground(new java.awt.Color(204, 255, 204));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 60, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("BAT");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 30, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("BOWL");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("ALL");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("BAT");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("BOWL");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("ALL");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jTextField11.setBackground(new java.awt.Color(204, 255, 204));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 60, 30));

        jTextField12.setBackground(new java.awt.Color(204, 255, 204));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 60, 30));

        jTextField13.setBackground(new java.awt.Color(204, 255, 204));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 60, 30));

        jTextField14.setBackground(new java.awt.Color(204, 255, 204));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 60, 30));

        jTextField15.setBackground(new java.awt.Color(204, 255, 204));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 60, 30));

        jTextField16.setBackground(new java.awt.Color(204, 255, 204));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 60, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("TEST");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 274, 40, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("ODI");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 264, 60, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("T20");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 264, 40, 20));

        jTextField17.setBackground(new java.awt.Color(204, 255, 204));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, -1));

        jTextField18.setBackground(new java.awt.Color(204, 255, 204));
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 80, -1));

        jTextField19.setBackground(new java.awt.Color(204, 255, 204));
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 80, -1));

        jTextField20.setBackground(new java.awt.Color(204, 255, 204));
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 80, -1));

        jTextField21.setBackground(new java.awt.Color(204, 255, 204));
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 80, -1));

        jTextField22.setBackground(new java.awt.Color(204, 255, 204));
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 80, -1));

        jTextField23.setBackground(new java.awt.Color(204, 255, 204));
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 80, -1));

        jTextField24.setBackground(new java.awt.Color(204, 255, 204));
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 80, -1));

        jTextField25.setBackground(new java.awt.Color(204, 255, 204));
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 80, -1));

        jTextField26.setBackground(new java.awt.Color(204, 255, 204));
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 80, -1));

        jTextField27.setBackground(new java.awt.Color(204, 255, 204));
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 80, -1));

        jTextField28.setBackground(new java.awt.Color(204, 255, 204));
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 80, -1));

        jTextField32.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 80, -1));

        jTextField34.setBackground(new java.awt.Color(204, 255, 204));
        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 80, -1));

        jTextField35.setBackground(new java.awt.Color(204, 255, 204));
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 80, -1));

        jTextField36.setBackground(new java.awt.Color(204, 255, 204));
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 80, -1));

        jTextField37.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 80, -1));

        jTextField38.setBackground(new java.awt.Color(204, 255, 204));
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 80, -1));

        jTextField39.setBackground(new java.awt.Color(204, 255, 204));
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 80, -1));

        jTextField40.setBackground(new java.awt.Color(204, 255, 204));
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 80, -1));

        jTextField41.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 80, -1));

        jTextField42.setBackground(new java.awt.Color(204, 255, 204));
        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 80, -1));

        jTextField43.setBackground(new java.awt.Color(204, 255, 204));
        jTextField43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField43ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 80, -1));

        jTextField44.setBackground(new java.awt.Color(204, 255, 204));
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, 80, -1));

        jTextField29.setBackground(new java.awt.Color(204, 255, 204));
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Get Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, 180, 50));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 160, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EDIT DETAILS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 30));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        name=jTextField1.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        dob=jTextField3.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        age= Integer.parseInt(jTextField4.getText());// TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        batting_style=jTextField5.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        bowling_style=jTextField6.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        team= jTextField7.getText();       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        batt=  Integer.parseInt(jTextField8.getText());       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        bowlt= Integer.parseInt(jTextField9.getText());           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        allt=Integer.parseInt(jTextField10.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        bato=  Integer.parseInt(jTextField11.getText());     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        bowlo= Integer.parseInt(jTextField12.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        allo= Integer.parseInt(jTextField13.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        bat2=  Integer.parseInt(jTextField14.getText());           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        bowl2= Integer.parseInt(jTextField15.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        all2= Integer.parseInt(jTextField16.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        matchest=Integer.parseInt(jTextField17.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        runt=Integer.parseInt(jTextField18.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        heighestt=Integer.parseInt(jTextField19.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        averaget=Integer.parseInt(jTextField20.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        matcheso=Integer.parseInt(jTextField21.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        runo=Integer.parseInt(jTextField22.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        heighesto=Integer.parseInt(jTextField23.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        averageo=Integer.parseInt(jTextField24.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        matches2=Integer.parseInt(jTextField26.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        run2=Integer.parseInt(jTextField26.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        heighest2=Integer.parseInt(jTextField27.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        average2=Integer.parseInt(jTextField28.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        wicketst=Integer.parseInt(jTextField34.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        averagest=Integer.parseInt(jTextField35.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        maidenst=Integer.parseInt(jTextField36.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        wicketso=Integer.parseInt(jTextField38.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        averageso=Integer.parseInt(jTextField39.getText());      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        maidenso=Integer.parseInt(jTextField40.getText());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        wickets2=Integer.parseInt(jTextField42.getText());       // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jTextField43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField43ActionPerformed
        averages2=Integer.parseInt(jTextField43.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField43ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        maidens2=Integer.parseInt(jTextField44.getText());       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        name=jTextField1.getText();
        role=jTextField29.getText();
        team= jTextField7.getText();
        dob= jTextField3.getText();
        averaget=Integer.parseInt(jTextField20.getText());
        average2=Integer.parseInt(jTextField28.getText());
        age= Integer.parseInt(jTextField4.getText());
        batting_style=jTextField5.getText();
        bowling_style=jTextField6.getText();
        batt=  Integer.parseInt(jTextField8.getText());
        bato=  Integer.parseInt(jTextField11.getText());
        bat2=  Integer.parseInt(jTextField14.getText());
        bowlt= Integer.parseInt(jTextField9.getText());
        bowlo= Integer.parseInt(jTextField12.getText());
        bowl2= Integer.parseInt(jTextField15.getText());
        allt=Integer.parseInt(jTextField10.getText());
        allo= Integer.parseInt(jTextField13.getText());
        matchest=Integer.parseInt(jTextField17.getText());
        all2= Integer.parseInt(jTextField16.getText());
        matcheso=Integer.parseInt(jTextField21.getText());
        matches2=Integer.parseInt(jTextField26.getText());
        runt=Integer.parseInt(jTextField18.getText());
        runo=Integer.parseInt(jTextField22.getText());
        run2=Integer.parseInt(jTextField26.getText());
        heighestt=Integer.parseInt(jTextField19.getText());
        heighesto=Integer.parseInt(jTextField23.getText());
        heighest2=Integer.parseInt(jTextField27.getText());
        averageo=Integer.parseInt(jTextField24.getText());
        wicketst=Integer.parseInt(jTextField34.getText());
        wicketso=Integer.parseInt(jTextField38.getText());
        wickets2=Integer.parseInt(jTextField42.getText());
        averagest=Integer.parseInt(jTextField35.getText());
        averageso=Integer.parseInt(jTextField39.getText());
        averages2=Integer.parseInt(jTextField43.getText());
        maidenst=Integer.parseInt(jTextField36.getText());
        maidenso=Integer.parseInt(jTextField40.getText());
        maidens2=Integer.parseInt(jTextField44.getText());
        try{
     DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","KEVAL","pass@123");
        Statement stmt=conn.createStatement();  
        stmt.executeQuery("update players set dob='"+dob+"' where name='"+name+"'");
        stmt.executeQuery("update players set age='"+age+"' where name='"+name+"'");
        stmt.executeQuery("update players set role='"+role+"' where name='"+name+"'");
        stmt.executeQuery("update players set team='"+dob+"' where name='"+name+"'");
        stmt.executeQuery("update players set batting_style='"+batting_style+"' where name='"+name+"'");
        stmt.executeQuery("update players set bowling_style='"+bowling_style+"' where name='"+name+"'");
        stmt.executeQuery("update bat set test='"+batt+"' where name='"+name+"'");
        stmt.executeQuery("update bat set odi='"+bato+"' where name='"+name+"'");
        stmt.executeQuery("update bat set t20='"+bat2+"' where name='"+name+"'");
        stmt.executeQuery("update bowl set test='"+bowlt+"' where name='"+name+"'");
        stmt.executeQuery("update bowl set odi='"+bowlo+"' where name='"+name+"'");
        stmt.executeQuery("update bowl set t20='"+bowl2+"' where name='"+name+"'");
        stmt.executeQuery("update average set test='"+averaget+"' where name='"+name+"'");
        stmt.executeQuery("update average set odi='"+averageo+"' where name='"+name+"'");
        stmt.executeQuery("update average set t20='"+average2+"' where name='"+name+"'");
        stmt.executeQuery("update run set test='"+runt+"' where name='"+name+"'");
        stmt.executeQuery("update run set odi='"+runo+"' where name='"+name+"'");
        stmt.executeQuery("update run set t20='"+run2+"' where name='"+name+"'");
        stmt.executeQuery("update highest set test='"+heighestt+"' where name='"+name+"'");
        stmt.executeQuery("update highest set odi='"+heighesto+"' where name='"+name+"'");
        stmt.executeQuery("update highest set t20='"+heighest2+"' where name='"+name+"'");
        stmt.executeQuery("update allr set test='"+allt+"' where name='"+name+"'");
        stmt.executeQuery("update allr set odi='"+allo+"' where name='"+name+"'");
        stmt.executeQuery("update allr set t20='"+all2+"' where name='"+name+"'");
        stmt.executeQuery("update matches set test='"+matchest+"' where name='"+name+"'");
        stmt.executeQuery("update matches set odi='"+matcheso+"' where name='"+name+"'");
        stmt.executeQuery("update matches set t20='"+matches2+"' where name='"+name+"'");
        stmt.executeQuery("update wickets set test='"+wicketst+"' where name='"+name+"'");
        stmt.executeQuery("update wickets set odi='"+wicketso+"' where name='"+name+"'");
        stmt.executeQuery("update wickets set t20='"+wickets2+"' where name='"+name+"'");
        stmt.executeQuery("update averages set test='"+averagest+"' where name='"+name+"'");
        stmt.executeQuery("update averages set odi='"+averageso+"' where name='"+name+"'");
        stmt.executeQuery("update averages set t20='"+averages2+"' where name='"+name+"'");
        stmt.executeQuery("update maidens set test='"+maidenst+"' where name='"+name+"'");
        stmt.executeQuery("update maidens set odi='"+maidenso+"' where name='"+name+"'");
        stmt.executeQuery("update maidens set t20='"+maidens2+"' where name='"+name+"'");
        JOptionPane.showMessageDialog(null,"updeted succesfully");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   name=jTextField1.getText();

        try{
     DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","KEVAL","pass@123");
        Statement stmt=conn.createStatement();
     
        ResultSet rs1= stmt.executeQuery("select * from players where name='"+name+"'");
        if(!rs1.next()){
             JOptionPane.showMessageDialog(null,"player not found");
                 jTextField1.setText(null);        
    jTextField10.setText(null);
    jTextField11.setText(null);
    jTextField12.setText(null);
    jTextField13.setText(null);
    jTextField14.setText(null);
    jTextField15.setText(null);
    jTextField16.setText(null);
    jTextField17.setText(null);
    jTextField18.setText(null);
    jTextField19.setText(null);
    jTextField1.setText(null);
    jTextField20.setText(null);
    jTextField21.setText(null);
    jTextField22.setText(null);
    jTextField23.setText(null);
    jTextField24.setText(null);
    jTextField25.setText(null);
    jTextField26.setText(null);
    jTextField27.setText(null);
    jTextField28.setText(null);
    jTextField29.setText(null);
    jTextField3.setText(null);
    jTextField32.setText(null);
    jTextField34.setText(null);
    jTextField35.setText(null);
    jTextField36.setText(null);
    jTextField37.setText(null);
    jTextField38.setText(null);
    jTextField39.setText(null);
    jTextField4.setText(null);
    jTextField40.setText(null);
    jTextField41.setText(null);
    jTextField42.setText(null);
    jTextField43.setText(null);
    jTextField44.setText(null);
    jTextField5.setText(null);
    jTextField6.setText(null);
    jTextField7.setText(null);
    jTextField8.setText(null);
    jTextField9.setText(null);
        }else{
        do{
           jTextField1.setText(rs1.getString(1));
           jTextField3.setText(rs1.getString(2));
           jTextField4.setText(rs1.getString(3));
           jTextField29.setText(rs1.getString(4));
           jTextField7.setText(rs1.getString(5));
           jTextField5.setText(rs1.getString(6));
           jTextField6.setText(rs1.getString(7));
        }while (rs1.next());
        ResultSet rs2=stmt.executeQuery("select * from bat where name in (select name from players where name='"+name+"')");
        while(rs2.next())
        {
            
           jTextField8.setText(rs2.getString(2));
           jTextField11.setText(rs2.getString(3));
           jTextField14.setText(rs2.getString(4));
          
        }
         ResultSet rs3=stmt.executeQuery("select * from bowl where name in (select name from players where name='"+name+"')");
        while(rs3.next())
        {
            
           jTextField9.setText(rs3.getString(2));
           jTextField12.setText(rs3.getString(3));
           jTextField15.setText(rs3.getString(4));
          
        }
        ResultSet rs4=stmt.executeQuery("select * from allr where name in (select name from players where name='"+name+"')");
        while(rs4.next())
        {
            
           jTextField10.setText(rs4.getString(2));
           jTextField13.setText(rs4.getString(3));
           jTextField16.setText(rs4.getString(4));
          
        }  
        ResultSet rs5=stmt.executeQuery("select * from matches where name in (select name from players where name='"+name+"')");
        while(rs5.next())
        {
            
           jTextField17.setText(rs5.getString(2));
           jTextField21.setText(rs5.getString(3));
           jTextField25.setText(rs5.getString(4));
           jTextField32.setText(rs5.getString(2));
           jTextField37.setText(rs5.getString(3));
           jTextField41.setText(rs5.getString(4));
          
        } 
        ResultSet rs6=stmt.executeQuery("select * from run where name in (select name from players where name='"+name+"')");
        while(rs6.next())
        {
            
           jTextField18.setText(rs6.getString(2));
           jTextField22.setText(rs6.getString(3));
           jTextField26.setText(rs6.getString(4));
          
        } 
        ResultSet rs7=stmt.executeQuery("select * from highest where name in (select name from players where name='"+name+"')");
        while(rs7.next())
        {
            
           jTextField19.setText(rs7.getString(2));
           jTextField23.setText(rs7.getString(3));
           jTextField27.setText(rs7.getString(4));
          
        } 
        ResultSet rs8=stmt.executeQuery("select * from average where name in (select name from players where name='"+name+"')");
        while(rs8.next())
        {
            
           jTextField20.setText(rs8.getString(2));
           jTextField24.setText(rs8.getString(3));
           jTextField28.setText(rs8.getString(4));
          
        } 
        ResultSet rs9=stmt.executeQuery("select * from wickets where name in (select name from players where name='"+name+"')");
        while(rs9.next())
        {
            
           jTextField34.setText(rs9.getString(2));
           jTextField38.setText(rs9.getString(3));
           jTextField42.setText(rs9.getString(4));
          
        } 
        ResultSet rs10=stmt.executeQuery("select * from wickets where name in (select name from players where name='"+name+"')");
        while(rs10.next())
        {
            
           jTextField35.setText(rs10.getString(2));
           jTextField39.setText(rs10.getString(3));
           jTextField43.setText(rs10.getString(4));
          
        } 
        ResultSet rs11=stmt.executeQuery("select * from wickets where name in (select name from players where name='"+name+"')");
        while(rs11.next())
        {
            
           jTextField36.setText(rs11.getString(2));
           jTextField40.setText(rs11.getString(3));
           jTextField44.setText(rs11.getString(4));
          
        } 
JOptionPane.showMessageDialog(null,"searched successfully");

         
       
stmt.close();
conn.close();}}
catch(Exception e){
     JOptionPane.showMessageDialog(null,e);
}     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try{
     DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","STUDENT1","pass@123");
        Statement stmt=conn.createStatement();
        stmt.executeQuery("delete from players where name='"+name+"'");
stmt.executeQuery("delete from matches where name='"+name+"'");  
stmt.executeQuery("delete from bat where name='"+name+"'");  
stmt.executeQuery("delete from bowl where name='"+name+"'");  
stmt.executeQuery("delete from allr where name='"+name+"'");  
stmt.executeQuery("delete from run where name='"+name+"'");  
stmt.executeQuery("delete from highest where name='"+name+"'");  
stmt.executeQuery("delete from average where name='"+name+"'");  
stmt.executeQuery("delete from wickets where name='"+name+"'");  
stmt.executeQuery("delete from averages where name='"+name+"'"); 
stmt.executeQuery("delete from maidens where name='"+name+"'"); 
   JOptionPane.showMessageDialog(null,"your player is deleted");}
  catch(Exception e){
  JOptionPane.showMessageDialog(null,e);
  }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 new welcome().setVisible(true); 
      dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fetch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private static javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
